"""Pydantic models for market data and freight forecasting."""

from typing import List, Optional
from pydantic import BaseModel, Field


# ─────────────────────────────────────────────────────────────────────────────
# Market Index Snapshot (single indicator at a point in time)
# ─────────────────────────────────────────────────────────────────────────────

class MarketIndicator(BaseModel):
    """A single market metric with trend statistics."""
    name: str = Field(..., description="Indicator name (e.g. 'Baltic Dry Index')")
    current_value: float = Field(..., description="Most recent available value")
    previous_value: float = Field(..., description="Value from one period ago")
    change_absolute: float = Field(..., description="Absolute change from previous")
    change_percent: float = Field(..., description="Percentage change from previous")
    trend_7d: float = Field(..., description="7-day rolling average")
    trend_30d: float = Field(..., description="30-day rolling average")
    direction: str = Field(..., description="'up', 'down', or 'stable'")
    unit: str = Field("", description="Unit of measurement (USD/bbl, index points, etc.)")
    data_source: str = Field("SYNTHETIC", description="Data provenance: SYNTHETIC/DEMO/REAL/LIVE")
    as_of_date: str = Field(..., description="ISO date of the most recent data point")


class MarketSnapshot(BaseModel):
    """Complete market conditions snapshot for a given analysis date."""
    bdi: MarketIndicator = Field(..., description="Baltic Dry Index")
    oil_price: MarketIndicator = Field(..., description="WTI Crude Oil price")
    commodity_price: Optional[MarketIndicator] = Field(None, description="Relevant commodity price")
    data_source: str = Field("SYNTHETIC", description="Overall data provenance label")
    disclaimer: str = Field(
        "Market data is SYNTHETIC and generated for educational/demonstration purposes only. "
        "Do NOT use for real trading decisions.",
        description="Mandatory data disclaimer",
    )


# ─────────────────────────────────────────────────────────────────────────────
# Freight Forecast Output
# ─────────────────────────────────────────────────────────────────────────────

class FreightForecast(BaseModel):
    """ML-generated freight rate forecast for a specific route and cargo type."""
    origin: str = Field(..., description="Loading port")
    destination: str = Field(..., description="Discharge port")
    cargo_type: str = Field(..., description="Cargo type")
    vessel_type: str = Field(..., description="Vessel class used for forecast")
    current_rate_usd_mt: float = Field(..., description="Most recent historical rate for this route")
    forecast_7d_usd_mt: float = Field(..., description="Predicted rate in 7 days")
    forecast_15d_usd_mt: float = Field(..., description="Predicted rate in 15 days")
    forecast_30d_usd_mt: float = Field(..., description="Predicted rate in 30 days")
    forecast_direction: str = Field(..., description="'up', 'down', or 'stable'")
    forecast_change_percent: float = Field(..., description="Predicted % change over 30 days")
    model_name: str = Field("RandomForestRegressor", description="ML model used")
    data_source: str = Field("SYNTHETIC", description="Data provenance")
    disclaimer: str = Field(
        "Freight rate forecasts are generated by an ML model trained on SYNTHETIC data. "
        "Not suitable for real commercial decisions.",
        description="Mandatory disclaimer",
    )


class ModelEvaluation(BaseModel):
    """Honest evaluation metrics for the freight forecasting ML model."""
    model_name: str = Field(..., description="Model identifier")
    mae: Optional[float] = Field(None, description="Mean Absolute Error (USD/mt)")
    rmse: Optional[float] = Field(None, description="Root Mean Square Error (USD/mt)")
    r2: Optional[float] = Field(None, description="R-squared coefficient of determination")
    train_samples: int = Field(..., description="Number of training samples")
    test_samples: int = Field(..., description="Number of test/holdout samples")
    features_used: List[str] = Field(default_factory=list, description="Feature names used in model")
    training_data_source: str = Field("SYNTHETIC", description="Data provenance label")
    note: str = Field("", description="Honest commentary on model quality and limitations")


class MarketAndForecastResult(BaseModel):
    """Combined market data + forecast result appended to ShippingResponse."""
    market_snapshot: MarketSnapshot = Field(..., description="Current market conditions")
    freight_forecast: Optional[FreightForecast] = Field(None, description="Rate forecast for this route")
    model_evaluation: Optional[ModelEvaluation] = Field(None, description="ML model performance metrics")
